name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Amazon Linux EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user                       
          key: ${{ secrets.EC2_SSH_KEY }}          
          port: 22
          script: |
            cd /home/ec2-user/my-app               
            git pull origin master                 
            npm install
            npm test
